### PR TITLE
Clay test

### PR DESCRIPTION
**Pull request by CBreshears**
This version of TileDB (ArrayDS) adds the capability of JPEG 2000 compression for images. To support this new compression requires pre-installation of the ODA OpenJPEG library. To build and install this library, use the following steps:

git clone https://github.com/OmicsDataAutomation/openjpeg.git
pushd openjpeg
mkdir build ; cd build
cmake ..
make; sudo make install
popd

The include files will be installed in /usr/local/include/openjpeg-2.3; the library files will be installed in
/usr/local/lib. Ensure that these paths are added to the appropriate environment variables. (TileDB only needs to have /usr/local/include in the INCLUDE_PATH during the build process.)

To add the JPEG 2000 compression within TileDB, add the -DENABLE_JPEG2K=True to the cmake command:

cmake -DENABLE_JPEG2K=True ..

No other special set up steps are needed to build, install, and use TileDB with JPEG 2000 compression support.

### CODE REVIEW

**Comment by CBreshears** [comment]
(Note: This request supercedes the original PR (#33). I think it still contains the spacing changes and parameter reordering that I did, which is ultimately superflous to the building and execution of the code.)

**Comment by mlathara** [comment]
Just curious, why does this PR have commits from all the way in Jan 2018? Wondering if its possible to rebase or something to only see the changes you've added...might make the review a bit easier...

**Comment by CBreshears** [comment]
I started making additions back then, but didn't have a full package ready to pull. Was ping-ponging back and forth between OpenJPEG and TileDB. Once the former was settled, I've completed a first pass on the latter.

**Comment by CBreshears** [comment]
Closing current PR. Will resubmit with modified version of JPEG integration.

**Pull request closed without merging**
